-- Unit tests for AmbientLFG matching logic.
-- Run from the repo root:  lua tests/run.lua
local spec = dofile("tests/spec.lua")
local describe, it, eq, ok = spec.describe, spec.it, spec.eq, spec.ok

local ns = {}
assert(loadfile("AmbientLFG_Match.lua"))("AmbientLFG", ns)
local M = ns.Match

describe("fuzzyPattern", function()
    local function matches(word, text)
        return text:lower():find(M.fuzzyPattern(word)) ~= nil
    end
    it("matches exact and stretched spellings", function()
        ok(matches("lura", "mythic lura lfg"), "exact")
        ok(matches("lura", "Lurra sell run"), "doubled r")
        ok(matches("lura", "LLuraa"), "doubled ends")
        ok(matches("lura", "LuraM tank needed"), "substring")
    end)
    it("does not match missing letters", function()
        eq(matches("lura", "lra group"), false)
        eq(matches("lura", "luna group"), false)
    end)
    it("handles pattern-magic characters in words", function()
        ok(matches("m+", "weekly m+ key"), "plus sign")
    end)
    it("matches a number exactly, never a longer one", function()
        -- a number in an ignore word means a quantity, so it may not run on
        ok(matches("+18", "M+18 NW LF tank"), "in a comment")
        ok(matches("+18", "done +18 earlier"), "mid-string")
        eq(matches("+18", "looking for +19 dps"), false, "different number")
        eq(matches("+18", "+188 lol"), false, "trailing digit")
        eq(matches("+2", "+22 key"), false, "+2 must not catch +22")
        eq(matches("18", "weekly 118 key"), false, "leading digit")
    end)
end)


describe("matchableText", function()
    it("drops kstring tokens, which are ids and not words", function()
        eq(M.matchableText("|Ks1969|k0000000000000000|k"), "")
        eq(M.matchableText("|Kk1234|k"), "")
    end)
    it("keeps plain text", function()
        eq(M.matchableText("LF1M tank Nerub-ar"), "LF1M tank Nerub-ar")
        eq(M.matchableText(""), "")
    end)
    it("stops a short ignore word hitting a token's characters", function()
        local haystack = M.matchableText("|Ks1969|k0000000000000000|k"):lower()
        eq(haystack:find(M.fuzzyPattern("ks")), nil)
    end)
    it("drops a title even when the group typed it", function()
        -- the whole reason rules were replaced by the search box: a listing
        -- named "+14" arrives as a token, so no keyword can ever see the level
        eq(M.matchableText("|Kf1234|k"), "")
    end)
end)


describe("rolesToString", function()
    it("names an empty set as any role, so nothing reads as broken", function()
        eq(M.rolesToString({}), "any role")
        eq(M.rolesToString(nil), "any role")
    end)
    it("reads back in a fixed order, not table order", function()
        eq(M.rolesToString({ DAMAGER = true, TANK = true }), "tank, dps")
    end)
end)

describe("resolveRaidRoles", function()
    it("follows the spec being played when nothing is pinned", function()
        eq(M.rolesToString(M.resolveRaidRoles(nil, "HEALER")), "healer")
    end)
    it("re-reads the spec rather than storing it, so a respec moves it", function()
        eq(M.rolesToString(M.resolveRaidRoles(nil, "TANK")), "tank")
        eq(M.rolesToString(M.resolveRaidRoles(nil, "DAMAGER")), "dps")
    end)
    it("a pinned set wins over the spec", function()
        eq(M.rolesToString(M.resolveRaidRoles({ TANK = true }, "DAMAGER")), "tank")
    end)
    it("a pinned empty set means every group, not a fallback to the spec", function()
        eq(M.rolesToString(M.resolveRaidRoles({}, "TANK")), "any role")
    end)
    it("an unreadable spec role alerts on everything rather than nothing", function()
        eq(M.rolesToString(M.resolveRaidRoles(nil, "")), "any role")
        eq(M.rolesToString(M.resolveRaidRoles(nil, "NONE")), "any role")
    end)
end)

describe("searchDescription", function()
    it("names the section", function()
        eq(M.searchDescription(M.CATEGORY_DUNGEONS, ""), "Dungeons")
        eq(M.searchDescription(M.CATEGORY_RAIDS, ""), "Raids")
    end)
    it("names the search box, which is the only key-level filter there is", function()
        eq(M.searchDescription(M.CATEGORY_DUNGEONS, "14-14"),
            "Dungeons, filtered by \"14-14\"")
    end)
end)

describe("raidDifficultyHint", function()
    local RAID, DUNGEON = M.CATEGORY_RAIDS, M.CATEGORY_DUNGEONS
    it("says nothing outside raids, where the box is a key range", function()
        eq(M.raidDifficultyHint(DUNGEON, "14-14"), nil)
        eq(M.raidDifficultyHint(nil, "heroic"), nil)
    end)
    it("confirms a difficulty the player already typed", function()
        local text, narrowed = M.raidDifficultyHint(RAID, "manaforge (hero")
        eq(narrowed, true)
        ok(text:find("heroic", 1, true), "names the difficulty")
    end)
    it("takes the same four-letter prefix the autocomplete answers to", function()
        eq(select(2, M.raidDifficultyHint(RAID, "(myth")), true)
        eq(select(2, M.raidDifficultyHint(RAID, "(norm")), true)
        eq(select(2, M.raidDifficultyHint(RAID, "lfr")), true)
        eq(select(2, M.raidDifficultyHint(RAID, "Heroic Manaforge")), true)
    end)
    it("suggests one when the search has none, since nothing else picks it", function()
        local text, narrowed = M.raidDifficultyHint(RAID, "manaforge")
        eq(narrowed, false)
        ok(text:find("every difficulty", 1, true), "says what it is watching now")
        ok(text:find("(heroic", 1, true), "says what to type")
    end)
end)

describe("listedBlockText", function()
    it("points a leader at the button that exists for them", function()
        ok(M.listedBlockText(true):find("Browse Groups", 1, true), "names the button")
    end)
    it("does not offer that button to anyone else, who does not have it", function()
        eq(M.listedBlockText(false):find("Browse Groups", 1, true), nil)
        ok(M.listedBlockText(false):find("taken down", 1, true), "says what does work")
    end)
    it("says watching is paused, which is what the player wants to know", function()
        ok(M.listedBlockText(true):find("paused", 1, true), "leader")
        ok(M.listedBlockText(false):find("paused", 1, true), "everyone else")
        ok(M.listedBlockText(true):find("taken down", 1, true), "says what resumes it")
    end)
end)

describe("shortName", function()
    it("strips the realm, which streams in late and only sometimes", function()
        eq(M.shortName("Lurra-Stormrage"), "Lurra")
        eq(M.shortName("Lurra"), "Lurra")
    end)
    it("survives a missing or unreadable name", function()
        eq(M.shortName(nil), "")
        eq(M.shortName(""), "")
    end)
end)

describe("stateLines", function()
    local function lines(over)
        local s = { enabled = true, armed = true, interval = 10 }
        for k, v in pairs(over or {}) do s[k] = v end
        return select(2, M.stateLines(s))
    end
    it("never leaves the empty list saying nothing is wrong when something is", function()
        -- the whole point: an empty list is when the player needs telling
        ok(lines({ enabled = false }):find("tick", 1, true), "off says how to turn it on")
        ok(lines({ armed = false }):find("Group Finder", 1, true), "idle says where to search")
        ok(lines({ listed = "your group is listed" }):find("listing", 1, true), "listed says why")
        ok(lines({ browsing = true }):find("close the Group Finder", 1, true), "browsing says why")
        ok(lines({ suspended = true }):find("retry", 1, true), "suspended says how to retry")
    end)
    it("tells a working addon's user there is nothing to do", function()
        ok(lines():find("Nothing to do", 1, true), "watching")
    end)
    it("answers before arming when the player's own group is listed", function()
        -- "search once to arm it" cannot be followed from the applicants view
        ok(lines({ armed = false, listed = "x" }):find("listing", 1, true), "order")
    end)
    it("keeps the status line and the empty line describing one state", function()
        local status = M.stateLines({ enabled = false })
        ok(status:find("Off", 1, true), "status names the state")
    end)
end)

describe("alertLine", function()
    it("names the group by the title it typed", function()
        eq(M.alertLine("LF1M tank", "Manaforge Omega (Heroic)", "Lurra-Stormrage"),
            "Group Finder: \"LF1M tank\" — Manaforge Omega (Heroic)")
    end)
    it("drops the activity when there is none", function()
        eq(M.alertLine("LF1M tank", nil, "Lurra"), "Group Finder: \"LF1M tank\"")
    end)
    it("never hands a secret to RaidWarning, which measures the line", function()
        local secret = {}
        _G.issecretvalue = function(v) return v == secret end
        -- an unreadable title falls back to the leader, who is real text
        eq(M.alertLine(secret, secret, "Lurra-Stormrage"), "Group Finder: Lurra")
        eq(M.alertLine(secret, "Manaforge", secret), "Group Finder: a group — Manaforge")
        _G.issecretvalue = nil
    end)
    it("always names something, so the banner is never a bare label", function()
        ok(M.alertLine(nil, nil, nil):find("a group", 1, true), "subject")
    end)
end)

describe("joinedGroup", function()
    it("stands down once the invite is accepted", function()
        eq(M.joinedGroup("inviteaccepted"), true)
    end)
    it("keeps watching through every status that is not being in the group", function()
        -- an invite can still be declined or time out, and applying is the
        -- point at which you most want to hear about a better group
        for _, status in ipairs({ "applied", "invited", "invitedeclined",
                "declined", "declined_full", "declined_delisted", "timedout",
                "cancelled", "failed", "none" }) do
            eq(M.joinedGroup(status), false, status)
        end
    end)
    it("does not stand down on a status it cannot read", function()
        local secret = {}
        _G.issecretvalue = function(v) return v == secret end
        eq(M.joinedGroup(secret), false)
        _G.issecretvalue = nil
        eq(M.joinedGroup(nil), false)
    end)
end)

describe("isOwnListing", function()
    it("knows your own listing by the flag the listing itself carries", function()
        eq(M.isOwnListing(true, "Someoneelse", nil), true)
        eq(M.isOwnListing(false, "Someoneelse", nil), false)
    end)
    it("falls back to the leader being someone in your own group", function()
        eq(M.isOwnListing(nil, "Lurra-Stormrage", { "Paul", "Lurra" }), true)
        eq(M.isOwnListing(nil, "Lurra", { "Paul", "Lurra-Stormrage" }), true)
        eq(M.isOwnListing(nil, "lurra", { "Lurra" }), true, "case")
    end)
    it("leaves every other group alone", function()
        eq(M.isOwnListing(false, "Stranger", { "Paul", "Lurra" }), false)
        eq(M.isOwnListing(false, "Paul", nil), false, "nothing of yours is listed")
    end)
    it("an unreadable leader name matches nobody, rather than everybody", function()
        eq(M.isOwnListing(nil, nil, { "Paul" }), false)
        eq(M.isOwnListing(nil, "", { "Paul" }), false)
    end)
    it("a secret field is read as not-mine, never as mine", function()
        local secret = {}
        _G.issecretvalue = function(v) return v == secret end
        eq(M.isOwnListing(secret, "Stranger", {}), false, "secret hasSelf")
        eq(M.isOwnListing(secret, "Paul", { "Paul" }), true, "falls through to names")
        eq(M.isOwnListing(nil, secret, { "Paul" }), false, "secret leader")
        _G.issecretvalue = nil
    end)
end)

describe("normalizeText", function()
    it("maps fullwidth letters to ASCII", function()
        eq(M.normalizeText("ＷＴＳ"), "WTS")
    end)
    it("maps mathematical bold to ASCII", function()
        eq(M.normalizeText("𝐖𝐓𝐒"), "WTS")
    end)
    it("maps small caps to ASCII", function()
        eq(M.normalizeText("ᴡᴛꜱ"), "wts")
    end)
    it("maps Cyrillic lookalikes to ASCII", function()
        eq(M.normalizeText("ШТЅ"):sub(-2), "TS", "T and S map; Sha has no lookalike")
    end)
    it("leaves plain ASCII untouched", function()
        eq(M.normalizeText("Mythic Lura LFG tank"), "Mythic Lura LFG tank")
    end)
end)

describe("matchesIgnoreWord", function()
    local IGNORES = { "wts", "sell", "boost", "carry" }
    local function ignored(title)
        return M.matchesIgnoreWord(M.normalizeText(title):lower(), IGNORES)
    end
    it("catches plain seller text", function()
        eq(ignored("[WTS Midnight Raids]"), "wts")
        eq(ignored("Selling mythic clears"), "sell")
        eq(ignored("cheap boost runs"), "boost")
    end)
    it("catches separator-evasion", function()
        eq(ignored("W T S mythic"), "wts")
        eq(ignored("W.T.S cheap"), "wts")
    end)
    it("catches Unicode-evasion", function()
        eq(ignored("ＷＴＳ raids"), "wts")
        eq(ignored("𝐒𝐞𝐥𝐥𝐢𝐧𝐠 gold runs"), "sell")
        eq(ignored("ᴡᴛꜱ ʟꜰ ʙᴜʏᴇʀꜱ"), "wts")
    end)
    it("passes legitimate groups", function()
        eq(ignored("Mythic Lura LFG need tank"), nil)
        eq(ignored("fresh sporefall prog"), nil)
    end)
end)


describe("roleIsOpen", function()
    local RAID, DUNGEON = M.CATEGORY_RAIDS, M.CATEGORY_DUNGEONS
    it("raid with 2 tanks is closed for tanks (the 2/4/14 bug)", function()
        eq(M.roleIsOpen("TANK", { TANK = 2, HEALER = 4, DAMAGER = 14 }, 20, RAID, 20), false)
    end)
    it("raid with 1 tank is open for tanks", function()
        eq(M.roleIsOpen("TANK", { TANK = 1, HEALER = 4, DAMAGER = 10 }, 15, RAID, 20), true)
    end)
    it("full raid is closed for everything", function()
        eq(M.roleIsOpen("DAMAGER", { TANK = 1, HEALER = 4, DAMAGER = 15 }, 20, RAID, 20), false)
    end)
    it("non-full raid is always open for dps", function()
        eq(M.roleIsOpen("DAMAGER", { TANK = 2, HEALER = 4, DAMAGER = 10 }, 16, RAID, 20), true)
    end)
    it("dungeon with a tank is closed for tanks", function()
        eq(M.roleIsOpen("TANK", { TANK = 1, HEALER = 1, DAMAGER = 1 }, 3, DUNGEON, 5), false)
    end)
    it("dungeon without a tank is open for tanks", function()
        eq(M.roleIsOpen("TANK", { TANK = 0, HEALER = 1, DAMAGER = 2 }, 3, DUNGEON, 5), true)
    end)
    it("unknown category falls back to remaining counts", function()
        eq(M.roleIsOpen("TANK", { TANK_REMAINING = 0 }, 3, nil, nil), false)
        eq(M.roleIsOpen("TANK", { TANK_REMAINING = 1 }, 3, nil, nil), true)
    end)
    it("unknown counts err toward open (spurious alert beats missed group)", function()
        eq(M.roleIsOpen("TANK", {}, nil, RAID, nil), true)
    end)
end)

os.exit(spec.finish())
