-- Unit tests for AmbientLFG matching logic.
-- Run from the repo root:  lua tests/run.lua
local spec = dofile("tests/spec.lua")
local describe, it, eq, ok = spec.describe, spec.it, spec.eq, spec.ok

local ns = {}
assert(loadfile("AmbientLFG_Match.lua"))("AmbientLFG", ns)
local M = ns.Match

describe("fuzzyPattern", function()
    local function matches(word, text)
        return text:lower():find(M.fuzzyPattern(word)) ~= nil
    end
    it("matches exact and stretched spellings", function()
        ok(matches("lura", "mythic lura lfg"), "exact")
        ok(matches("lura", "Lurra sell run"), "doubled r")
        ok(matches("lura", "LLuraa"), "doubled ends")
        ok(matches("lura", "LuraM tank needed"), "substring")
    end)
    it("does not match missing letters", function()
        eq(matches("lura", "lra group"), false)
        eq(matches("lura", "luna group"), false)
    end)
    it("handles pattern-magic characters in words", function()
        ok(matches("m+", "weekly m+ key"), "plus sign")
    end)
end)

describe("normalizeText", function()
    it("maps fullwidth letters to ASCII", function()
        eq(M.normalizeText("ＷＴＳ"), "WTS")
    end)
    it("maps mathematical bold to ASCII", function()
        eq(M.normalizeText("𝐖𝐓𝐒"), "WTS")
    end)
    it("maps small caps to ASCII", function()
        eq(M.normalizeText("ᴡᴛꜱ"), "wts")
    end)
    it("maps Cyrillic lookalikes to ASCII", function()
        eq(M.normalizeText("ШТЅ"):sub(-2), "TS", "T and S map; Sha has no lookalike")
    end)
    it("leaves plain ASCII untouched", function()
        eq(M.normalizeText("Mythic Lura LFG tank"), "Mythic Lura LFG tank")
    end)
end)

describe("matchesIgnoreWord", function()
    local IGNORES = { "wts", "sell", "boost", "carry" }
    local function ignored(title)
        return M.matchesIgnoreWord(M.normalizeText(title):lower(), IGNORES)
    end
    it("catches plain seller text", function()
        eq(ignored("[WTS Midnight Raids]"), "wts")
        eq(ignored("Selling mythic clears"), "sell")
        eq(ignored("cheap boost runs"), "boost")
    end)
    it("catches separator-evasion", function()
        eq(ignored("W T S mythic"), "wts")
        eq(ignored("W.T.S cheap"), "wts")
    end)
    it("catches Unicode-evasion", function()
        eq(ignored("ＷＴＳ raids"), "wts")
        eq(ignored("𝐒𝐞𝐥𝐥𝐢𝐧𝐠 gold runs"), "sell")
        eq(ignored("ᴡᴛꜱ ʟꜰ ʙᴜʏᴇʀꜱ"), "wts")
    end)
    it("passes legitimate groups", function()
        eq(ignored("Mythic Lura LFG need tank"), nil)
        eq(ignored("fresh sporefall prog"), nil)
    end)
end)

describe("parseRule", function()
    it("splits words and role tags", function()
        local rule = M.parseRule("mythic lura +tank")
        eq(rule.words[1], "mythic")
        eq(rule.words[2], "lura")
        eq(rule.roles[1], "TANK")
        eq(rule.category, nil, "raids is the default (no explicit category)")
    end)
    it("understands category tags", function()
        eq(M.parseRule("keys +dungeon").category, M.CATEGORY_DUNGEONS)
        eq(M.parseRule("lura +raid").category, M.CATEGORY_RAIDS)
    end)
    it("rejects unknown tags and empty rules", function()
        local rule, err = M.parseRule("lura +banana")
        eq(rule, nil)
        ok(err:find("banana"), "error names the bad tag")
        eq(M.parseRule("   "), nil)
    end)
    it("round-trips through ruleToString", function()
        local rule = M.parseRule("mythic lura +tank +dungeon")
        eq(M.ruleToString(rule), "mythic lura +tank +dungeon")
    end)
end)

describe("roleIsOpen", function()
    local RAID, DUNGEON = M.CATEGORY_RAIDS, M.CATEGORY_DUNGEONS
    it("raid with 2 tanks is closed for tanks (the 2/4/14 bug)", function()
        eq(M.roleIsOpen("TANK", { TANK = 2, HEALER = 4, DAMAGER = 14 }, 20, RAID, 20), false)
    end)
    it("raid with 1 tank is open for tanks", function()
        eq(M.roleIsOpen("TANK", { TANK = 1, HEALER = 4, DAMAGER = 10 }, 15, RAID, 20), true)
    end)
    it("full raid is closed for everything", function()
        eq(M.roleIsOpen("DAMAGER", { TANK = 1, HEALER = 4, DAMAGER = 15 }, 20, RAID, 20), false)
    end)
    it("non-full raid is always open for dps", function()
        eq(M.roleIsOpen("DAMAGER", { TANK = 2, HEALER = 4, DAMAGER = 10 }, 16, RAID, 20), true)
    end)
    it("dungeon with a tank is closed for tanks", function()
        eq(M.roleIsOpen("TANK", { TANK = 1, HEALER = 1, DAMAGER = 1 }, 3, DUNGEON, 5), false)
    end)
    it("dungeon without a tank is open for tanks", function()
        eq(M.roleIsOpen("TANK", { TANK = 0, HEALER = 1, DAMAGER = 2 }, 3, DUNGEON, 5), true)
    end)
    it("unknown category falls back to remaining counts", function()
        eq(M.roleIsOpen("TANK", { TANK_REMAINING = 0 }, 3, nil, nil), false)
        eq(M.roleIsOpen("TANK", { TANK_REMAINING = 1 }, 3, nil, nil), true)
    end)
    it("unknown counts err toward open (spurious alert beats missed group)", function()
        eq(M.roleIsOpen("TANK", {}, nil, RAID, nil), true)
    end)
end)

os.exit(spec.finish())
